#!/bin/bash
set -e

### ───────────────────────────────────────────
### 1) CONFIG
### ───────────────────────────────────────────
API_URL="https://v2thu7qsrd.execute-api.eu-central-1.amazonaws.com/dev"

# Öffentliche Domain der Anwendung
APP_DOMAIN="habify.leitnersoft.com"

# Tatsächlicher S3-Bucket für das SPA-Frontend
S3_BUCKET="habify-dev-frontend"

# Deine echte CloudFront Distribution ID
CLOUDFRONT_ID="EFTPSI92OL0WY"

# Cognito
COGNITO_POOL_ID="eu-central-1_t8xE8WR5L"
COGNITO_CLIENT_ID="69hbfjjmcjs6438gm0ir2b275s"
COGNITO_DOMAIN="https://habify-dev.auth.eu-central-1.amazoncognito.com"

FRONTEND_DIR="$(pwd)"
BUILD_DIR="$FRONTEND_DIR/dist"

echo "🚀 Starte Deployment..."
echo "Arbeitsverzeichnis: $FRONTEND_DIR"


### ───────────────────────────────────────────
### 2) Generate .env.production (clean)
### ───────────────────────────────────────────
echo "🔧 Erzeuge .env.production…"

cat > .env.production <<EOF
# Automatically generated by deploy.sh

VITE_API_URL="$API_URL"
VITE_APP_DOMAIN="$APP_DOMAIN"
VITE_CLOUDFRONT_URL="$APP_DOMAIN"

# Cognito
VITE_COGNITO_DOMAIN="$COGNITO_DOMAIN"
VITE_COGNITO_USER_POOL_CLIENT_ID="$COGNITO_CLIENT_ID"
VITE_COGNITO_REDIRECT_URI="https://$APP_DOMAIN/login"
EOF

echo "✅ .env.production erfolgreich erstellt"


### ───────────────────────────────────────────
### 3) Disable .env.local (prevent localhost redirect)
### ───────────────────────────────────────────
if [ -f .env.local ]; then
    echo "⚠️ Deaktiviere .env.local (Production-Build darf keinen localhost enthalten)"
    mv .env.local .env.local.backup
fi


### ───────────────────────────────────────────
### 4) Build frontend (Production Mode)
### ───────────────────────────────────────────
echo "🏗️  Baue Frontend (Production)…"
NODE_ENV=production npm run build
echo "✅ Build abgeschlossen"


### ───────────────────────────────────────────
### 5) Upload build to S3
### ───────────────────────────────────────────
echo "📤 Lade Dateien zu S3 hoch (Bucket: $S3_BUCKET)…"
aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" --delete
echo "✅ Upload abgeschlossen"


### ───────────────────────────────────────────
### 6) CloudFront invalidation
### ───────────────────────────────────────────
echo "🧹 Invalidiere CloudFront Cache (ID: $CLOUDFRONT_ID)…"
aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_ID" \
    --paths "/*"
echo "✅ CloudFront Cache invalidiert"


### ───────────────────────────────────────────
### 7) Restore .env.local
### ───────────────────────────────────────────
if [ -f .env.local.backup ]; then
    echo "🔄 Stelle .env.local wieder her"
    mv .env.local.backup .env.local
fi


### ───────────────────────────────────────────
### 8) Summary
### ───────────────────────────────────────────
echo ""
echo "🎉 Deployment abgeschlossen!"
echo "─────────────────────────────────────────────"
echo "Frontend Domain:  https://$APP_DOMAIN"
echo "CloudFront:       https://$CLOUDFRONT_URL"
echo "S3 Bucket:        $S3_BUCKET"
echo "API URL:          $API_URL"
echo ""
echo "Cognito:"
echo "  - Domain:        $COGNITO_DOMAIN"
echo "  - User Pool ID:  $COGNITO_POOL_ID"
echo "  - Client ID:     $COGNITO_CLIENT_ID"
echo "  - Redirect URI:  https://$APP_DOMAIN/login"
echo "─────────────────────────────────────────────"
echo "🚀 Alles sauber deployed!"
